### ISSUE TITLE
Développeur frontend (H/F) #React

### ISSUE THREAD

**Issue by AlmosniShirley** [AlmosniShirley/JobsBuildRH#11]
# Contexte du recrutement ?

## La petite histoire de Tarmac Technologies et leur positionnement actuel

Tarmac Technologies est une startup dans l’univers de l’aviation qui a vu le jour en janvier 2020 grâce au croisement de trois destins incroyables, tous passionnés d’aviation : les destins de [Maud Payan](https://www.linkedin.com/in/maudpayan/), d’[Anthoine Dusselier](https://www.linkedin.com/in/anthoine-dusselier-039154100/) et de Delphine. 

Quand Maud m’a raconté son histoire, j’ai immédiatement pensé au petit qui joue avec son avion dans le clip [Stardust](https://www.dailymotion.com/video/x704j) : une jeune fille brillante, rêveuse, qui, un jour, s’est rendue aux portes ouvertes de l’aéroclub et elle s’est dit immédiatement “je veux être pilote de ligne !”. 

Les choses se sont enchaînées : baptême de l’air, elle vole toute seule à 15 ans, passe son brevet à 17 ans, rentre en classes préparatoires pour rejoindre l’ENAC. Mais finalement, elle fera Centrale et bifurque dans le domaine de l’ingénierie. Elle a toujours les avions dans un coin de la tête : elle fait un master Aéronautique au Canada, passe les étapes théoriques pour être pilote de ligne mais rate de très peu la pratique. Elle fait ensuite X-HEC Entrepreneur et là elle se dit “Je veux monter une startup dans le domaine de l’aviation”. C’est à ce moment-là qu’elle rencontre Anthoine…

Anthoine, lui, a fait Polytechnique et réalise son stage de césure à San Francisco dans le domaine de la Data. Dans le cadre de cette expérience, un soir, sans conviction, il décide de se rendre à une soirée Networking. Ce soir-là, il rencontre Delphine qui travaille en tant qu’adjointe chef d’escale Air France KLM à l’aéroport de San Francisco…

Delphine fait partie de ses chanceux français expatriés au USA grâce à l’obtention de la Green Card. Elle a toujours été passionnée par les statistiques et le domaine aérien. Elle commence en tant qu’agent sachant parler français et évolue vers le métier de Chef d’Escale. Elle partage avec Anthoine ses problèmes dans son quotidien à l’escale : “’je n’ai aucun outil pour avoir des données statistiques sur l’escale. En traquant les process durant les opérations au sol, on pourrait améliorer la performance de l’escale”” 

Ainsi commence la folle histoire de Tarmac Technologies !

<img width="685" alt="Capture d’écran 2024-01-18 à 14 29 16" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/c21092d8-bb25-4764-843f-948c3b277b78">

Le positionnement actuel de Tarmac Technologies est le suivant : **il s’agit d’une solution SAAS visant à aider ses clients à optimiser les opérations au sol, c’est-à-dire tout ce qui se passe au niveau de l’avion sur le Tarmac, entre l’atterrissage et le décollage. Cela s’appelle “la touchée” dans le jargon de l’aviation.** 

Voici quelques exemple d’opérations : 

Un avion long-courrier reste au sol en moyenne 2 heures minimum et pendant ce lapse de temps, il se passe beaucoup de choses ! 

- Débarquement des passagers et de leurs bagages.
- Mettre du fuel.
- Service de nettoyage. 
- Chargement/Déchargement des bagages
- Checking des passagers
- Changement d’équipage
- Nourriture à charger à bord 
…

Il y a, en moyenne, 25 opérations à faire sur ce temps très restreint. 

Par ailleurs, il y a une certaine complexité car 

Ces tâches sont faites par des prestataires différents (plus de 10 prestataires différents peuvent être utilisés sur certaines touchées). 
Ces tâches sont interdépendantes. 

L’apport de valeur de Tarmac Technologies est le suivant : 

- Communication et tracking en temps réel. 
- Centralisation de l’information : par le passé, une compagnie pouvait recevoir une dizaine de rapports manuels pour seulement un vol. 
- Identifier les éventuels couacs dans la chaîne : derrière cet aspect il y a des implications légales très fortes car chaque retard/ problème implique des pénalités financières fortes. 
- Des services additionnels : facturation, message obligatoire, mesure de performance, bâtir et/ou ajuster des contrats sur de vraies données.  
- Tarmac Technologies crée donc de la valeur et de la visibilité là où il n’y en avait pas. 

## Chronologies des événements 

`Les premiers jalons` 

L’entreprise est immatriculée en janvier 2020. 

`Période d’euphorie `

Le projet a de très belles perspectives ! Ils ne cessent de remporter des concours orientés innovation et entrepreneuriat. 

<img width="155" alt="Capture d’écran 2024-01-18 à 14 32 38" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/6114d5c7-eed2-4718-9831-25484df04c1a">

En février 2020, Maud et Anthoine partent à San Francisco pour déployer leur produit commercialement. Pendant cette même période, ils signent leur LOI pour une future levée de fonds.

`Douche froide et incertitude`

La levée de fonds prévue ne se fait finalement pas dans ce contexte Covid qui a bloqué mondialement le secteur aérien. Le modèle économique reposant sur les vols, il y a  des incertitudes sur la faisabilité/pérennité du business.

`On ne lâche rien ! `

On est sur une période de confinement et ils se retrouvent tous ensemble pour bosser à fond le produit pendant 3 mois (entre mars et juin 2020) sur la base de leurs connaissances terrain. 

Ils peaufinent les specs, travaillent à fond le design et finissent par sortir un produit très quali ! 

`La relance `

Les opérations aériennes reprennent en juin 2020 et ils reçoivent un go pour travailler avec leur 1ère compagnie aérienne française cliente. 

Au fur et à mesure, le bouche à oreille fonctionne et d’autres compagnies s’intéressent à leur solution : 

- Des compagnies aériennes cargo qui fonctionnent toujours malgré les confinements 
- Une nouvelle compagnie aérienne française début 2021. 

Cette bouffée d’air frais dans leur business et un prêt sur l’honneur à hauteur de plusieurs milliers d’euros permet de réaliser le recrutement de [Clément Roque](https://www.linkedin.com/in/cl%C3%A9ment-roque-%F0%9F%92%BB-a23a6879/), Tech Lead backend. 

`Passage à un autre échelle`

En juin 2021, ils signent leur plus gros contrat avec une compagnie majeure de l’aérien mondial. Ils se déploient sur plus de 130 aéroports dans le monde où l’outil fonctionne en temps réel. 

L’entreprise décolle. La notoriété de leurs clients leur permet de faire un bond en avant. 

De septembre 2021 à l’été 2022, ils signent avec la majorité des compagnies françaises long courrier.

De 2021 à 2022, leur CA connaît une évolution de plus de 250%. 

## Focus actualité recrutement 

Ainsi, dans un tel contexte de croissance, ils recrutent un profil de développeur.se frontend avec une expérience significative sur la technologie React. 

Niveau expérience, ils ciblent à partir de 5 ans d’expérience. 

Les enjeux sont multiples côté frontend : 

- Interconnexions avec l’app mobile

- Interface web en react

- Une expérience utilisateur à perfectionner à plusieurs niveaux.

## Lexique à connaître et définition des rôles chez Tarmac Technologies

Il n’y a pas de grille salariale dans la hiérarchie d’entreprise. C’est plutôt une petite entreprise. Cependant, Maud, m’a tout de même donné sa définition de junior et de senior. 

**Développeur.se junior** : une personne qui a de bonnes notions en développement, une bonne logique, mais qui, au quotidien, a besoin de se faire accompagner pour perfectionner ses réflexes et sa maîtrise des enjeux techniques (langages, méthodologie, métier). 

**Développeur.se senior** : 

une personne qui 

- a une vision plus globale du SI.

- est capable de gérer des features de A à Z. 

- arrive à bien challenger le besoin métier. 

- sait anticiper les éventuelles contraintes business/techniques. 

- propose une solution qui se rapproche grandement du besoin exprimé par l’utilisateur. 

# Quelle entreprise vas-tu rejoindre ?

## Date existence

Janvier 2020

## Nombre de personnes au sein de l’entreprise et au sein de l’équipe technique

8 personnes au total dans l’entreprise dont 4 personnes au sein de l’équipe technique. 

Ils travaillent aussi avec quelques freelances sur la partie mobile. 

## Localisation

L’ensemble de l’équipe technique est en full remote.
L’équipe OSS (op, sales, support) est quant à elle basée rue Saint Honoré, Paris 1er. 

# Quelle organisation d’entreprise vas-tu rejoindre ?

## La configuration des équipes

<img width="886" alt="Capture d’écran 2024-01-18 à 14 36 55" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/af352b72-1827-43a5-aca7-2f8f1a21ae6d">

Ils ont des profils et de personnalités très différents dans l’équipe : [Héloïse](https://www.linkedin.com/in/heloise-t-a42b48136/) est plutôt Junior et sort d’une école d’informatique, [Charles](https://www.linkedin.com/in/charles-piegad-248957200/) est un profil plutôt Junior qui a fait un parcours en reconversion. Quant à Clément, il est le senior de l’équipe et a fait une école d’ingénieur.

<img width="800" alt="Capture d’écran 2024-01-18 à 14 37 42" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/17c89186-b021-4e8f-8cff-d3187e650421">

## La stack technique actuelle  

<img width="797" alt="Capture d’écran 2024-01-18 à 14 38 39" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/c5f82af3-16a8-45e8-a842-ee5d33330510">

## Environnement méthodologique 

<img width="797" alt="Capture d’écran 2024-01-18 à 14 39 18" src="https://github.com/AlmosniShirley/JobsBuildRH/assets/10773051/eabfa234-6617-4cdb-a443-21f1e6b2efe8">

# Les profils attendus ?

## Les compétences opérationnelles 

Une personne qui a déjà une bonne expérience en développement React (au moins 2 ans sur React) et au moins 3 ans d’expérience professionnelle en tant que développeur.se, et qui correspondent à la définition d’un profil senior défini auparavant (cf. Lexique à connaître et définition des rôles chez Tarmac Technologies).

`L’idée étant de recruter une personne qui est :`

- Apte à challenger l’existant, avec pragmatisme et bienveillance. 

- Complémentaire à Clément sur la partie frontend afin d’apporter un bagage de connaissances sur ce langage et ses subtilités. 

- Accompagner les personnes juniors de l'équipe. *je vais avoir besoin d’une personne qui est réellement à mes côtés, soudés sur les projets, avec laquelle il y a de l’entraide mutuelle et non juste une posture hiérarchique. Je sais que j’ai encore beaucoup de choses à apprendre en développement frontend* (Héloïse)

- Une personne qui a de bonnes compétences frontend de façon plus générale : des compétences purement CSS, de bonnes connaissances en matière de responsivité. 

- Une personne qui a de bons fondamentaux techniques et cela passe donc par une certaine capacité à : 

- [ ] Avoir de bons réflexes en développement : questionner le besoin, sortir du dogmatisme technique, penser tests, viser un code lisible, maintenable et réutilisable. 

- [ ] Avoir une connaissance de quelques patterns en développement. 

- [ ] S’intéresser aux métiers, aux usages, aux comportements.

- [ ] Anticiper les impacts futurs de son code, voir sur le long terme.

## Les challenges techniques 

- Projet AGOA (web et mobile) et amélioration des interfaces. Il leur manque une navigation plus fluide sur le web et entre les différentes interfaces. 

- Projet facturation (Invoicing) avec la création d’une nouvelle interface en React TypeScript. 

- Projet CCO (centre de contrôle opérationnel) : faire en sorte que toutes les compagnies aient un suivi de leur flotte d’avions en temps réel (challenge sur les 6 prochains mois). 

## Les soft skills attendues

Une personne pédagogue et patiente car il est question de bien cerner les enjeux métier de la solution, les besoins utilisateurs (ce ne sont pas des technophiles en face) mais aussi de faire preuve d’écoute, de patience en tant que mentor. 

**Une personne qui pense la technique comme un moyen au service d’un besoin et non comme une fin en soi**. 

Cela se traduit par :

- [ ] Cette capacité à bien comprendre le besoin en face. La personne n’est pas dans un rôle d’exécutant mais dans un rôle stratégique avec, un amont du temps de réflexion, de discussion, de conception.  

- [ ] Cette aptitude à nuancer, à peser le pour et le contre des solutions envisagées.  

- [ ] Cette capacité à bien anticiper les potentielles contraintes techniques futures. 

- Une personne **câblée Egoless** : une personne qui est capable de partager son code, de prendre la critique non pas directement de façon personnelle mais plutôt de bien comprendre les erreurs commises dans une démarche d’amélioration continue. De plus, une personne qui ne met pas de hiérarchie dans la critique. Les critiques sont bonnes à prendre d’où qu’elles viennent : business, personnes plus juniors, etc. 

- Une personne **curieuse** : cela passe par la compréhension du métier, par une ouverture aux autres équipes mais aussi par cette volonté d’apprendre, de sortir de sa bulle de connaissances, de sa zone de confort. Cela passe aussi par une démarche de recherche personnelle, de discussion, d’échange dans les moments de bugs. 

- Une personne avec de **l’enthousiasme** : dans un contexte qui démarre, il y aura beaucoup de remise en question, de pivot éventuel tant au niveau de la solution qu’au niveau des choix techniques. Cela exige donc d’avoir une énergie positive dans l’équipe. Lorsque le problème arrive la première réaction n’est pas d’aller directement dans des formules relativement négatives voire toxiques “c’est la faute de…” “l’utilisateur ne comprend rien…” “je suis dans une équipe vraiment nulle…”, “ce code c’est de la merde…” mais plutôt de chercher à comprendre collectivement ce qui n’a pas fonctionné pour s’orienter vers de nouvelles hypothèses, solutions. Il est donc question d’être davantage cablé “problem solver” avec une réelle empathie pour l’utilisateur final. 

`Sur quoi se basent essentiellement la décision du recrutement ?`

Ce qui fera la différence ce sont les éléments suivants : 

- Surtout le mindset !

- De la motivation et de l’enthousiasme à faire partie de l’aventure, à faire grandir leur solution, à se réjouir des réussites collectives. 

- Évidemment de bonnes aptitudes techniques : raisonnement/logique autour du code plus qu’une connaissance parfaite d’un langage. 

Ce qui ne passe pas du tout chez eux : 

`Les personnalités toxique et cela se traduit par :`

- Un dialogue compliqué, un ego démesuré.

- Comportement individualiste : rétention d’information, une personne qui s’isole de l’équipe, qui code uniquement pour elle. 
Des personnes qui attachent aucune importance à la qualité, qui dénigrent les tests, etc. 

## Les évolutions de carrières possibles 

Cette personne pourra, à l’avenir, et comme toute personne de l’équipe technique, discuter des choix d’évolution qu’elle souhaitera au sein de l’entreprise, soit devenir spécialiste/expert dans sa techno, soit axer son évolution au sein de l’entreprise en prenant des responsabilités plus managériales.

## Le processus de recrutement

**1ere étape** : rencontre à la fois culture fit et technique. Cela dure une heure. Clément, en session de pair programming, cherche davantage à comprendre le raisonnement du candidat, comment il réagit face au questionnement technique, s’il a de bons réflexes de code. La partie culture fit est prépondérante dans cette première phase du processus de recrutement. 

**2eme étape** : il s’agit de deux entretiens : l’un avec Héloïse pour parler frontend et voir si le matching se fait, l’autre avec Maud, davantage centré sur une étude de cas sur un cas d’usage du quotidien. 

**3ème étape** : test technique plus approfondi. L’idée est d’évaluer davantage les compétences frontend, les problématiques d’API, le clean code, la culture des tests. Restitution faite par Clément et Héloïse avec partage de tips. 

**Dernière étape** : déjeuner en visu avec un aller-retour sur la journée pris en charge par l’entreprise. L’idée est de voir toute l’équipe avant de partir sur une proposition d’embauche. 

Le processus de recrutement est plutôt rapide : 3 semaines maximum. 

# La rémunération, les classiques et les avantages

## La rémunération cible

Target de rémunération : 50 K€ 

## Les classiques et les avantages

- Prime basée sur les performances de l’entreprise. Cette prime est donnée en deux temps durant l’année. 
Bien qu’ils soient tous en remote, ils ont des tickets restaurant (Swile) tous les jours à hauteur de 8 € (50% pris en charge par l’entreprise). 

- BSPCE avec une valorisation très forte.

- Mutuelle santé Alan dont 50% est pris en charge par l’entreprise. Il est possible de mettre dessus son conjoint. 

- Enveloppe de 100 € par an pour tous les achats professionnels (veille technique ou autre). 

# L’environnement de travail global

## Les moyens, les outils de travail 

- Notion au niveau des specs. 

- Slack pour la communication au quotidien.
  
- Jira pour les tickets et le suivi des bugs. 

- Git et GitHub.

- Front avec Amplify. 

- MacBook Pro. 

- Documentation sur Confluence ou Notion. 

## La politique remote

**Le périmètre remote** : les personnes basées en France, idéalement à 5 heures maximum en train. 

**Côté installation à domicile** : double écran, clavier, souris. 

**Déplacements** pris en charge ainsi que le logement lorsqu’il faut venir dans les locaux. 

**Moments de rencontre** : une fois tous les deux mois, 4 jours (du lundi au jeudi / ou du mardi au vendredi). 

**Fréquence des rencontres** au bureau: 4 à 5 fois maximum dans l’année. 

**Autres moments de cohésion d’équipe** : deux séminaires (un en hiver et un autre en été). Ils ont été au ski, dans le bassin d’Arcachon, à Montpellier, en Bretagne…

## Espace veille et formation

- Pair programming toutes les semaines.

- Kata toutes les deux semaines. 

- Atelier meetup toutes les deux semaines : exposer un sujet libre. Récemment, Héloïse a partagé le sujet suivant: “Qu’est-ce qu’un développeur frontend”. Quant à Clément, il a partagé ce sujet : “Qu’est-ce que mettre en prod ?”. 

- Si besoin, prise en charge des formations demandées par les personnes au sein de l’équipe technique.

# Les plus/les moins du projet d’entreprise ?

## Les moins

- Petite équipe technique donc le relationnel est bien plus fort que si vous deviez rejoindre une grande équipe où l’effort de cohésion peut être plus dilué. 

- Aventure entrepreneuriale : je le vois comme un point positif mais cela peut rebuter certaines personnes car forcément il y a les contraintes de la startup dont l’avenir est forcément plus incertain qu’une entreprise qui existe depuis des années. *Nous avons conscience que tout n’est pas rose mais une chose est sûre, quoiqu’il advienne, la protection des salariés est et sera notre priorité. Nous avons une trésorerie vraiment saine. Nous n’avons pas grossi trop vite* (Maud)

- Une rémunération plus attractive pourrait éventuellement faire la différence. 

## Les plus

- Une structure qui incarne très bien la culture de la qualité, tant au niveau des recrutements, qu’au niveau des interactions avec les utilisateurs jusqu’au code. Ce n’est pas uniquement une histoire de tests, d’outils, de TDD. C’est plus globalisé et c’est forcément plus efficace. 

- Trésorerie saine avec un market fit atteint aujourd’hui. 

- Entreprise ambitieuse qui aime vraiment son produit, ses clients. Il y a une réelle culture métier, une empathie côté utilisateur. 

- Un bon équilibre vie pro/ perso ce qui évite une fatigue émotionnelle, un développement improductif. 

- Culture de la délégation : il est possible de faire bouger les lignes, de prendre des sujets à fort enjeu, même en tant que débutant chez eux. Il n’y a pas de chasse gardée, de savoir et de pouvoir autocentré sur quelques personnes. Il n’y a personne qui détient la vérité. 

- Bonne culture technique : meetups internes, outils collaboratifs modernes. 

- Full remote avec une possibilité de rejoindre un cadre qui encourage la cohésion d’équipe : pratiques agiles mais aussi séminaires d’entreprise. 

- Du temps donné à l’amélioration continue : ils prennent ce temps nécessaire pour discuter, pour impulser de nouveaux outils, de nouvelles idées, pour challenger le savoir de chacun et les problèmes rencontrés au quotidien. Les gens sont disponibles pour aider, accompagner, écouter. 

Si cela vous intéresse, n'hésitez pas à postuler en m'adressant un message à l'adresse suivante : almosnishirley@gmail.com

**Comment by Kalem8** [comment]
Un goal
