### ISSUE TITLE
VP of Engineering (H/F) 

### ISSUE THREAD

**Issue by AlmosniShirley** [AlmosniShirley/JobsBuildRH#23]
<img width="295" alt="Capture d’écran 2024-10-08 à 12 55 54" src="https://github.com/user-attachments/assets/2685a4ca-6866-4152-9b16-083ed8f6b5e5">

### 1. Contexte du recrutement ?

`1.1 La petite histoire d’Altavia et leur positionnement actuel`

[Altavia cloud](https://altavia.co/fr) est une business unit d’Altavia. Fondée en 1983, Altavia est le premier groupe de communication international et indépendant dédié au Retail, étendant son influence à 45 pays sur quatre continents. 

Plus concrètement, Altavia travaille avec de grands comptes et de grandes marques telles que Carrefour, l’Oréal pour concevoir tout le marketing et la communication off line telles que des brochures, des PLV, des goodies, des stickers, et des catalogues, tout cela en étroite collaboration avec des fournisseurs dédiés pour les réaliser. 

Altavia Cloud a donc vu le jour, en septembre 2023, dans le but d’être porteuse d’une solution logicielle permettant d’industrialiser, de digitaliser et d’automatiser tout ce travail de coordination entre les clients et le réseau des fournisseurs. En interne, le mot marketplace a été prononcé mais c’est bien plus que cela !  Il y a aussi, une dimension de conseil et de customisation du besoin client, en prenant en compte les contraintes business, légales et de transport propres à chaque pays. 

Une solution historique a été développée en interne. Mais il est question, avec Altavia Cloud, d’aller plus loin sur de nombreux aspects : modernisation technique afin de scaler la solution, refonte du SI intégrant les meilleurs SaaS (Salesforce, Ivalua, Mulesoft, SAP), création d’une architecture data moderne, mise en place d’infrastructures Cloud GCP, meilleure design avec une refonte totale côté frontend, automatisation de bout en bout, de la commande à la livraison, optimisation du pricing en temps réel, calcul de l'empreinte carbone, usage des technologies IA, …

`1.2 Focus actualité recrutement `

L’actualité recrutement s’inscrit dans un contexte d’entreprise **en pleine transformation**. 

Il y aussi bien une nouvelle business unit, Altavia Cloud, ce qui implique des changements organisationnels mais aussi une nouvelle solution logicielle, ce qui implique de nouveaux recrutements et de profonds changements techniques. 

Ces changements se feront en douceur et prendront en compte la qualité de l’existant : l’historique client, la connaissance business, les compétences techniques déjà présentes dans l'équipe. L’ancienne plateforme a 7 ans d'existence. 

Ainsi, l’objectif est d’harmoniser, de consolider et de bâtir une solution pérenne et scalable, tout cela avec une réelle vision produit et des méthodes de développement orientées sur la qualité logicielle, tout comme chez un éditeur  de logiciel.  

Ainsi, dans ce contexte d’entreprise, ils ont projeté les recrutements suivants : 

- VP of engineering (H/F)
- Un développeur frontend, React, TypeScript (H/F)
- Un développeur plus orienté fullstack, React, Node (H/F)
- Un lead designer (H/F)
- Un senior product manager (H/F)
- Un senior product manager avec un background tech (H/F)
- Un Lead Product Manager (H/F)

### 2. Quelle entreprise vas-tu rejoindre ?

`2.1 Date existence`

Septembre 2023

`2.2 Nombre de personnes au sein de l’entreprise et au sein de l’équipe technique`

**Global** 

2500 personnes travaillent chez Altavia dans le monde entier (bureaux dans 45 pays). 

20 personnes travaillent chez Altavia Cloud. 

**Tech**

Au sein d’Altavia Cloud, l’équipe technique est composée de 11 personnes. 

`2.3 Chiffres business`

- 40 millions d'achats annuels sur la plateforme.

- 10 clients Grands Groupes. Altavia vise un usage plus massif en intégrant des clients SMB (Small and Medium Business). 

- 500 utilisateurs mensuels, calculés sur l’ancienne plateforme. 

- Business model : commissions sur les transactions qui passent sur la plateforme, et facturation de certaines options de la solution SaaS. 

`2.4 Localisation`

Il sont basés à Saint-Ouen avec un format de télétravail hybride (6.2 La politique télétravail)

Métro 13 - station Garibaldi
Métro 14 - station Saint-Denis- Pleyel 

### 3. Quelle organisation d’entreprise vas-tu rejoindre ?

`3.1 La culture d'entreprise `

<img width="576" alt="Capture d’écran 2024-10-08 à 12 09 33" src="https://github.com/user-attachments/assets/a4529a9b-b5a0-4a8b-adeb-0dc0eebd80f5">

`3.2 La configuration des équipes `

<img width="572" alt="Capture d’écran 2024-10-08 à 12 25 53" src="https://github.com/user-attachments/assets/bc03e15a-f640-4f5d-9823-29b93b2ff4ee">

`3.3 La stack technique passée et actuelle  `

<img width="570" alt="Capture d’écran 2024-10-08 à 12 40 41" src="https://github.com/user-attachments/assets/53670cf9-36ed-4544-b321-97264c7162e9">
<img width="567" alt="Capture d’écran 2024-10-08 à 12 41 07" src="https://github.com/user-attachments/assets/b429ba45-618e-48f9-baf9-fc90243bc13b">

`3.4 Environnement méthodologique `

<img width="571" alt="Capture d’écran 2024-10-08 à 12 39 10" src="https://github.com/user-attachments/assets/9c3fef02-cd96-4c07-b81f-1b64b06db9e4">

`3.5 Fonctionnalités de la solution et défis futurs `

<img width="572" alt="Capture d’écran 2024-10-08 à 12 40 03" src="https://github.com/user-attachments/assets/b7369058-c5c0-492d-9686-d9a0950e96f8">

### 4. Le profil attendu ?

`4.1 Les compétences opérationnelles `

La future recrue est rattachée au Technical Leader. Il s’agit d’un poste intermédiaire ou senior. Pour ce poste clef, il est attendu les compétences suivantes. 

Une personne qui : 

La future recrue sera le bras droit d’[Edouard](https://www.linkedin.com/in/edouardmercier/), CTO, à la croisée des chemins entre le produit, le business et l'ingénierie. 

Ainsi, pour ce profil clef, il est attendu les compétences opérationnelle suivantes : 

**Sur la partie produit (30%)**

- **Capacité à comprendre le produit sous toutes ses coutures** et ses subtilités afin de bien cerner les enjeux des nouvelles fonctionnalités, tant techniquement que sur le plan business et faire les bons choix de priorisation : quelles sont les fonctionnalités qui peuvent être positives pour le client ? Quelles sont leur plus-value ? etc. La future recrue travaille étroitement avec les équipes Produit pour définir et anticiper les nouvelles fonctionnalités à horizon 6 mois. 

- **Priorisation des fonctionnalités et répartition des tâches au sein de l’équipe technique**.  La future recrue va être régulièrement sollicitée en avance de phase pour qualifier, estimer, concevoir de manière macroscopique des fonctionnalités à venir, en collaboration étroite avec l'équipe Produit. Cela permettra à l'équipe d'anticiper encore mieux les évolutions de la plateforme, et nous permettra de disposer constamment d'un coup d'avance, ce qui est un pré-requis pour réaliser une bonne conception et laisser le temps à l'équipe technique de mieux se préparer aux défis à relever liés à ces évolutions, de laisser maturer les options techniques.

- **Dialogue avec le Métier, le Produit et la Direction** pour apporter un regard critique, et des conseils au sujet de la vision produit. Dans ce contexte, la future recrue doit donc avoir un certain sens des enjeux business et **de bonnes aptitudes à échanger en anglais** (anglais parlé et écrit). Elle est donc capable de parler au métier et de traduire les besoins utilisateurs à la sauce IT. 

**Sur la partie technique (30% du poste)**

- **Capacité à avoir une certaine hauteur de vue pour comprendre le SI** dans sa globalité, tant sur des aspects backend que frontend. 

- **Avoir de bonnes compétences techniques explorées dans des environnements professionnels variés** : une expérience sur des langages techniques différents et/ou dans des contextes techniques différents (“from scratch” ou contexte legacy ou contexte de migration technique ou contexte de petite équipe où tout est à bâtir, etc.).

- La personne doit avoir de bonnes bases côté Node, TypeScript et idéalement en Java pour asseoir une certaine crédibilité. La personne doit avoir **de bons fondamentaux techniques**.

- De très bonnes compétences sur des problématiques **d’architecture** et sur de **bonnes pratiques de développement**. La future recrue va impulser encore plus loin la culture technique. Elle doit être capable de fédérer sur des choix techniques, sur de nouveaux outils, solutions, approches, méthodologies, tout en anticipant les éventuels blocages, contraintes business comme techniques. 

**Sur la partie Encadrement (40% du poste)**

- Bien qu’il s’agit d’un poste à responsabilité hiérarchique qui implique l’encadrement des technical leaders, au niveau de l'état d’esprit, on est avant tout sur **une posture de Servant Leader** dans le sens où la personne endosse un rôle de guide, de mentor, de soutien notamment auprès des personnes plus juniors dans l’équipe technique. 

- Elle **sait aussi donner des arguments liés à son expertise** pour appuyer tel choix technologique plutôt qu’un autre. 

- La future recrue **sait aussi s’entourer des compétences de l’équipe pour mener à bien les projets** de refonte et les différents chantiers techniques. Cette personne n’est pas toute seule dans sa tour d’ivoire comme unique décisionnaire mais dans un collectif d’équipe où chacun apporte sa pierre à l’édifice, du plus junior au plus senior. 

- La future recrue **est aussi pédagogue et a une bonne dose d’empathie** pour bien dialoguer avec le métier et se mettre à leur place, pour faire remonter les difficultés du terrain auprès de la Direction et donner de bonnes impulsions au changement dans une démarche d’amélioration continue, tant au niveau du code qu’au niveau de la communication au sein de l’équipe et avec les personnes extérieures à l’équipe. 

- Toujours sur la partie managériale, la future recrue **peut aussi anticiper et/ou annoncer ses besoins en matière de recrutement** dans l’équipe et donc participer à la consolidation de sa future équipe, tant en participant au processus de recrutement qu’en contribuant à l’onboarding et à la montée en compétences des futures recrues. 

A côté de toutes ces tâches, sur le long terme, la future recrue peut pleinement aller plus loin dans l’impulsion de la culture technique en : 

- Mettant en place des meetups internes. 

- En participant à des conférences techniques. 

- En étant, tout simplement, un peu plus évangélisateur.trice à l'extérieur sur les sujets techniques rencontrés chez Altavia Cloud. 

Message d'Edouard : _“ il y a un terrain de jeu énorme. Il y a de la place. On peut se répartir les sujets sans problème. Je lui donnerai autant que cette personne peut et veut prendre”._

`4.2 Ce qu’il vous faut pour bien réaliser ce poste`

Les aptitudes humaines prennent vie dans un contexte d’entreprise qui a ses valeurs et sa culture. 

Ainsi les valeurs exposées par Altavia Cloud sont les suivantes : 

- **Sens du collectif** : il y a l’idée de voir une solution grandir et prendre forme à travers un collectif. Les réussites comme les potentiels ratés sont collectifs. Il n’y pas la désignation d’un coupable quand ça va mal. C’est ensemble qu’ils gèrent les difficultés. 
Ainsi, au niveau des softs skills, **une personne team player** qui sait s’inscrire dans un groupe et qui sait s’y adapter, est forcément une aptitude attendue. 

- **Ouverture d’esprit** : ce point s’incarne notamment dans le fait qu’ils souhaitent aller vers plus de changement/de modernisation au niveau des pratiques, au niveau des features, au niveau de l’amélioration de la qualité produit, au niveau de l’architecture. Ainsi, au niveau des soft skills, il est attendu **une personne ouverte d’esprit, au dialogue et non dogmatique techniquement** qui part sur des idées toutes faites sur l’étagère. Elle aura pour mission de bien comprendre l’existant, la réalité des utilisateurs, l’environnement technique, pour ensuite prioriser les sujets et faire les bons choix techniques avec pragmatisme et réalisme. 

- **Sens de l’engagement** : Altavia Cloud est encore au stade de sa structuration. Ainsi, au niveau des soft skills il est attendu **une personne positive, enthousiaste, qui a un réel sentiment d’appartenance à l’entreprise**, au produit, qui fait son job mais qui a la liberté totale d’aller au-delà, d’en faire plus si elle sent qu’en prenant telle initiative, en faisant telle suggestion, le produit va dans le bon sens. La Direction a grandement besoin d’être challengée. Une personne qui a davantage une posture d'exécutante, ça ne va pas vraiment matcher. 

- **Sens de la critique et du dialogue** : étant donné qu’ils sont encore en phase de structuration, il y a encore une vision produit et technique en construction. Ainsi, au niveau des soft skills, il est attendu **une personne qui a conscience de l’imperfection organisationnelle et technique** et qui est capable de formuler comme d’écouter la critique, qui est capable d’être tournée vers le dialogue, les réflexions autour du produit et surtout qui est en mesure de se remettre en question en cas de débat/désaccord. 

- **Culture de l'expérimentation, du droit à l’erreur** en ayant une réelle volonté d’explorer de nouveaux terrains de jeux techniques via la veille mais aussi via la culture du partage de la connaissance en interne. Ainsi, au niveau des soft skills, **une personne passionnée** qui réalise, elle-même, déjà beaucoup de veille technique se plaira comme un poisson dans l’eau. Elle sera dans son élément avec des individus qui sauront l’élever vers le haut et qui auront envie d’en savoir plus sur ce qu’elle peut apporter au quotidien et dans le cadre de sa veille technique. 

Encore, une fois, il n’est pas attendu une personne qui coche toutes les cases techniques, ou encore toutes les cases au niveau des soft skills mais il est attendu une personne engagée, motivée, consciente de l’existant, des difficultés, qui sait faire preuve d’ouverture d’esprit, de dialogue, de curiosité métier comme technique et qui sait affirmer ses opinions avec bienveillance et respect. 

Ils cherchent avant tout **de véritables partenaires, de véritables piliers fiables et solides** pour construire le produit et toutes ses briques techniques, ensemble, et non un.e simple salarié.e qui exécute les ordres.

`4.3 Le processus de recrutement`

- **1ere étape** : pré-qualification par BUILD RH puis envoie du dossier de candidature au sein des équipes recrutement et tech chez Altavia. 

- **2ème étape** : entretien généraliste de 45 minutes avec [Edouard](https://www.linkedin.com/in/edouardmercier/), CTO, et [Hamza](https://www.linkedin.com/in/hamza-khalifa-726b11151/), technical leader, pour faire connaissance, présenter l’entreprise, l’environnement technique, et en savoir plus sur l’expérience professionnelle du candidat. 

- **3eme étape** : entretien technique d’1h30 sous forme d’exercice à réaliser en direct via un partage d’écran, avec au préalable des instructions d’installation transmises via un fichier Readme. L’idée est d’observer les pratiques du candidat, de voir si ce dernier est à l’aise avec son environnement. Il est question de jauger le niveau de maturité technique mais aussi d’évaluer les bonnes pratiques de développement. 
+feedback 

- **Dernière étape** : si après concertation collective les avis sont favorables, il y a proposition d’embauche. 

Sur la fin du processus de recrutement, il y a une immersion au sein des locaux pour rencontrer de façon plus informelle les futurs collègues ainsi que la direction produit ([Nicolas](https://www.linkedin.com/in/nicolasbeladen/)) et la direction d’entreprise ([Laetitia)](https://www.linkedin.com/in/gazelanthoine/).

### 5. La rémunération, les classiques et les avantages

`5.1 La rémunération cible`

+/- 120 K€ 

`5.2 Les classiques et les avantages`

- Ticket de restaurant à hauteur de 8 € 
- Mutuelle dont la part employeur est à 50%
- Prise en charge des transports à hauteur de 50%, idem pour la mobilité douce (vélo ou trottinette) avec parking et prise compris
- CE d’entreprise pour la billetterie spectacle et pour profiter de réductions sur des séjours

### 6. L’environnement de travail global

`6.1 Les moyens, les outils de travail `

- La type de machine est choisi par le candidat : MAC ou Windows ou Linux + 2eme écran 
- Licence VSCODE. C’est ok aussi pour JetBrains
- Suite Google workplace
- Google meet 
- Slack 
 
Côté outillage, il n’y a pas d’économie de bouts de chandelle pour bien travailler. 

`6.2 La politique remote`

- 3 jours au bureau dont deux jours imposés qui sont le lundi et le mercredi chaque semaine. Le 3eme jour au bureau est libre.

- Cependant, une fois par mois, ce troisième jour au bureau est imposé et il s’agit du jeudi. 

`6.3 Espace veille et formation`

Tout est à bâtir et ils sont ouverts à toutes les suggestions pour faire progresser techniquement et au niveau du métier les équipes : sponsoring et accueil des événements, participation à des événements techniques, création de contenu…

### 7. Les plus/les moins du projet d’entreprise ?

`7.1 Les moins`

- **Petite équipe technique** donc le relationnel est bien plus fort que si vous deviez rejoindre une grande équipe où l’effort de cohésion peut être plus dilué. 

- **Passage d’une culture propre à chaque business unit à une harmonisation organisationnelle** comme technique pour tout le Groupe Altavia. C’est un changement de paradigme qui prendra du temps. 

- **Pas la possibilité de faire du full remote** ce qui peut être perçu comme un point négatif par de nombreuses personnes dans l’univers de la tech. 

- **Nécessité de mieux se professionnaliser sur ces sujets** : cadre de veille,formation et RSE. 

- **En phase de structuration** : je le vois comme un point positif mais cela peut rebuter certaines personnes car forcément il y a des contraintes au quotidien, des changements, des discussions et un cadre organisationnel et technique imparfait. 

`7.2 Les plus`

- **Possibilité d’avoir un poste réellement fullstack**, du frontend au backend. 

- **Forte proximité avec le métier** ce qui permet d’avoir une vision terrain et de construire un soft pleinement en phase avec les attendus business. 

- **Management qui délègue et donne de l’autonomie à ses équipes** avec un véritable terrain d’évolution professionnelle. Il est possible de faire bouger les lignes, de prendre des sujets à fort enjeu. Il n’y a pas de chasse gardée, de savoir et de pouvoir autocentrés sur quelques personnes. La future recrue pourra réellement créer son futur poste. 

- Tous les avantages de **la startup avec la stabilité financière du Grand Groupe**. 

- Structure qui a une **dimension internationale**. 

- Cadre de travail qui **attache de l’importance à la qualité** sous toutes ses formes : qualité des recrutements, qualité de la relation client et qualité de code. 

- **Stack moderne et cohérente** et socle technique bien pensé. 

- **Investissement dans un bon niveau de communication** : prendre le temps de se concerter, de se dire les choses, une bonne culture du feedback, un droit à l’erreur, une sécurité psychologique, une démarche de remise en question et d’amélioration continue, une équipe disponible, solidaire. 

- Il y a de nombreux **défis techniques comme business**. 

<img width="1006" alt="Capture d’écran 2024-10-08 à 12 56 57" src="https://github.com/user-attachments/assets/c8938084-c2c7-4f60-8590-1a815a12c949">

N'hésitez pas à postuler via mon adresse mail : almosnishirley@gmail.com

**Comment by ErwanAliasr1** [comment]
C'est clair, c'est complet, les offres comme on les aime.

**Comment by kw-andy** [comment]
Super intéressant et surtout super clair !

**Comment by AlmosniShirley** [comment]
Merci !
