### ISSUE TITLE
Développeur Fullstack Senior à la recherche de nouvelles opportunités ! #NodeJS

### ISSUE THREAD

**Issue by AlmosniShirley** [AlmosniShirley/JobsBuildRH#7]
Vous avez [ici](https://www.canva.com/design/DAF3sfLpC8M/XkMwMVCYXA2ZjpvM-4Z8jw/view?utm_content=DAF3sfLpC8M&utm_campaign=designshare&utm_medium=link&utm_source=editor) la présentation détaillée de sa recherche de Job !

**Comment by Neroshamaya** [comment]
Bonjour Shirley, 

Je suis interessé par le poste.
Mon linkedin pour plus d'infos sur mon parcours: https://www.linkedin.com/in/paul-legeay-59b16827/
Mon cv:
[Nodejs Backend Developer.pdf](https://github.com/AlmosniShirley/JobsBuildRH/files/13991110/Nodejs.Backend.Developer.pdf)

Cordialement,

Paul

PS: Super présentation au passage, ça m'a fait réfléchir sur mes expériences passées.
